// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations use the direct (non-pooled) Supabase connection; the running app
  // uses the pooled DATABASE_URL via the driver adapter in src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
