// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Plain PostgreSQL: the CLI (migrate/generate) and the running app share a single
  // DATABASE_URL (the app reaches it via the driver adapter in src/lib/prisma.ts).
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
